# Change these first
owner: grodrigo # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
TZ: America/Argentina/Buenos_Aires

sites:
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Recreo
    url: https://recreo.gba.gob.ar
  - name: RECREO_SITE
    url: $RECREO_SITE
  - name: RECREO_SITE
    url: $RECREO_SITE/admin/login
    method: POST
    body: '{ "email": "$RECREO_USER", "password": "$RECREO_PASSWORD"}'
    expectedStatusCodes:
      - 419
  - name: recreo api test
    url: https://test.recreo.gba.gob.ar/graphql
    method: POST
    headers:
      - 'clientinformation: web'
      - 'Content-Type: application/json'
    body: '{"query":"mutation\n{login_simple(grant_type: \"password\",\n    client_id: \"4\",\n    client_secret: \"$RECREO_CLIENT_SECRET\",\n    $RECREO_API_USERNAME: \"recreo.admin@yopmail.com\",\n    $RECREO_API_PASSWORD: \"admin\") \n{access_token}\n}","variables":{}}'

assignees: # Users to assign downtime issues (optional)
  - grodrigo

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime grodrigo status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
